# yamllint disable-line rule:truthy
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "SukramJ"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "SukramJ"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
    groups:
      npm:
        patterns:
          - "*"
