/**
 * German translations.
 */

import type { ScheduleTranslations } from "./types";

export const de: ScheduleTranslations = {
  weekdays: {
    short: {
      monday: "Mo",
      tuesday: "Di",
      wednesday: "Mi",
      thursday: "Do",
      friday: "Fr",
      saturday: "Sa",
      sunday: "So",
    },
    long: {
      monday: "Montag",
      tuesday: "Dienstag",
      wednesday: "Mittwoch",
      thursday: "Donnerstag",
      friday: "Freitag",
      saturday: "Samstag",
      sunday: "Sonntag",
    },
  },
  domains: {
    switch: "Schalter",
    light: "Licht",
    cover: "Rollladen",
    valve: "Ventil",
  },
  conditions: {
    fixed_time: "Feste Zeit",
    astro: "Astro",
    fixed_if_before_astro: "Fest wenn vor Astro",
    astro_if_before_fixed: "Astro wenn vor Fest",
    fixed_if_after_astro: "Fest wenn nach Astro",
    astro_if_after_fixed: "Astro wenn nach Fest",
    earliest: "Frühester",
    latest: "Spätester",
  },
  common: {
    schedule: "Zeitplan",
    loading: "Zeitplandaten werden geladen...",
    entityNotFound: "Entität {entity} nicht gefunden",
    clickToEdit: "Klicken Sie auf einen Zeitabschnitt, um den Zeitplan zu bearbeiten",
    edit: "{weekday} bearbeiten",
    cancel: "Abbrechen",
    save: "Speichern",
    addTimeBlock: "+ Zeitblock hinzufügen",
    copySchedule: "Zeitplan kopieren",
    pasteSchedule: "Zeitplan einfügen",
    undo: "Rückgängig",
    redo: "Wiederholen",
    undoShortcut: "Rückgängig (Strg+Z)",
    redoShortcut: "Wiederholen (Strg+Y)",
    exportSchedule: "Exportieren",
    importSchedule: "Importieren",
    exportTooltip: "Zeitplan als JSON-Datei exportieren",
    importTooltip: "Zeitplan aus JSON-Datei importieren",
    exportSuccess: "Zeitplan erfolgreich exportiert",
    importSuccess: "Zeitplan erfolgreich importiert",
    unsavedChanges: "Ungespeicherte Änderungen",
    saveAll: "Alle speichern",
    discard: "Verwerfen",
    confirmDiscardChanges: "Sie haben ungespeicherte Änderungen. Möchten Sie diese verwerfen?",
  },
  climate: {
    from: "Von",
    to: "Bis",
    baseTemperature: "Basistemperatur",
    baseTemperatureDescription: "Temperatur für nicht geplante Zeiträume",
    temperaturePeriods: "Temperaturperioden",
    editSlot: "Bearbeiten",
    saveSlot: "Speichern",
    cancelSlotEdit: "Abbrechen",
    sensorNotSupported: "Sensor-Entität {entity} hat keinen Klima-Zeitplantyp.",
    noScheduleData: "Entität {entity} stellt keine Zeitplandaten bereit.",
  },
  device: {
    toggleCompactView: "Kompaktansicht",
    toggleFullView: "Vollansicht",
    enableDragDrop: "Drag & Drop Modus aktivieren",
    disableDragDrop: "Drag & Drop Modus deaktivieren",
    level: "Stufe",
    levelOn: "Ein",
    levelOff: "Aus",
    slat: "Lamellenposition",
    addEvent: "Ereignis hinzufügen",
    editEvent: "Ereignis bearbeiten",
    time: "Zeit",
    duration: "Dauer",
    rampTime: "Rampenzeit",
    state: "Zustand",
    weekdays: "Wochentage",
    channels: "Zielkanäle",
    condition: "Bedingung",
    astroSunrise: "Sonnenaufgang",
    astroSunset: "Sonnenuntergang",
    astroOffset: "Astro-Offset (Min.)",
    maxEntriesReached: "Maximale Anzahl an Einträgen erreicht ({max})",
    confirmDelete: "Möchten Sie dieses Ereignis wirklich löschen?",
  },
  errors: {
    failedToChangeProfile: "Fehler beim Wechseln des Profils: {error}",
    failedToSaveSchedule: "Fehler beim Speichern des Zeitplans: {error}",
    failedToPasteSchedule: "Fehler beim Einfügen des Zeitplans: {error}",
    invalidSchedule: "Ungültiger Zeitplan: {error}",
    failedToExport: "Fehler beim Exportieren des Zeitplans: {error}",
    failedToImport: "Fehler beim Importieren des Zeitplans: {error}",
    invalidImportFile: "Ungültiges Dateiformat. Bitte wählen Sie eine JSON-Datei.",
    invalidImportFormat: "Ungültiges JSON-Format in der Datei.",
    invalidImportData: "Ungültige Zeitplandaten: {error}",
    incompatibleEntity:
      "Entität {entity} ist keine kompatible Zeitplan-Entität (erfordert schedule_type 'default' und schedule_api_version 'v1.0')",
    insufficientPermissions: "Sie haben keine Berechtigung für diese Aktion.",
  },
  warnings: {
    title: "Validierungswarnungen",
    noWarnings: "Keine Probleme erkannt",
  },
  validationMessages: {
    blockEndBeforeStart: "Block {block}: Die Endzeit liegt vor der Startzeit",
    blockZeroDuration: "Block {block}: Der Block hat keine Dauer",
    invalidStartTime: "Block {block}: Ungültige Startzeit",
    invalidEndTime: "Block {block}: Ungültige Endzeit",
    temperatureOutOfRange: "Block {block}: Temperatur außerhalb des Bereichs ({min}-{max}°C)",
    invalidSlotCount: "Ungültige Anzahl an Slots: {count} (erwartet 13)",
    invalidSlotKey: "Ungültiger Slot-Schlüssel: {key} (muss eine Ganzzahl 1-13 sein)",
    missingSlot: "Slot {slot} fehlt",
    slotMissingValues: "Slot {slot} fehlt ENDTIME oder TEMPERATURE",
    slotTimeBackwards: "Slot {slot}: Zeit läuft rückwärts: {time}",
    slotTimeExceedsDay: "Slot {slot}: Zeit überschreitet 24:00: {time}",
    lastSlotMustEnd: "Der letzte Slot muss um 24:00 enden",
    scheduleMustBeObject: "Zeitplandaten müssen ein Objekt sein",
    missingWeekday: "Fehlender Wochentag: {weekday}",
    invalidWeekdayData: "Ungültige Daten für {weekday}",
    weekdayValidationError: "{weekday}: {details}",
  },
};
