/**
 * English translations.
 */

import type { ScheduleTranslations } from "./types";

export const en: ScheduleTranslations = {
  weekdays: {
    short: {
      monday: "Mo",
      tuesday: "Tu",
      wednesday: "We",
      thursday: "Th",
      friday: "Fr",
      saturday: "Sa",
      sunday: "Su",
    },
    long: {
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
    },
  },
  domains: {
    switch: "Switch",
    light: "Light",
    cover: "Cover",
    valve: "Valve",
  },
  conditions: {
    fixed_time: "Fixed Time",
    astro: "Astro",
    fixed_if_before_astro: "Fixed if before Astro",
    astro_if_before_fixed: "Astro if before Fixed",
    fixed_if_after_astro: "Fixed if after Astro",
    astro_if_after_fixed: "Astro if after Fixed",
    earliest: "Earliest",
    latest: "Latest",
  },
  common: {
    schedule: "Schedule",
    loading: "Loading schedule data...",
    entityNotFound: "Entity {entity} not found",
    clickToEdit: "Click on a time slot to edit the schedule",
    edit: "Edit {weekday}",
    cancel: "Cancel",
    save: "Save",
    addTimeBlock: "+ Add Time Block",
    copySchedule: "Copy schedule",
    pasteSchedule: "Paste schedule",
    undo: "Undo",
    redo: "Redo",
    undoShortcut: "Undo (Ctrl+Z)",
    redoShortcut: "Redo (Ctrl+Y)",
    exportSchedule: "Export",
    importSchedule: "Import",
    exportTooltip: "Export schedule to JSON file",
    importTooltip: "Import schedule from JSON file",
    exportSuccess: "Schedule exported successfully",
    importSuccess: "Schedule imported successfully",
    unsavedChanges: "Unsaved changes",
    saveAll: "Save all",
    discard: "Discard",
    confirmDiscardChanges: "You have unsaved changes. Do you want to discard them?",
    close: "Close",
  },
  climate: {
    from: "From",
    to: "To",
    baseTemperature: "Base Temperature",
    baseTemperatureDescription: "Temperature for unscheduled periods",
    temperaturePeriods: "Temperature Periods",
    editSlot: "Edit",
    saveSlot: "Save",
    cancelSlotEdit: "Cancel",
    removeSlot: "Remove",
    sensorNotSupported: "Sensor entity {entity} does not have a climate schedule type.",
    noScheduleData: "Entity {entity} does not provide schedule data.",
  },
  device: {
    toggleCompactView: "Compact view",
    toggleFullView: "Full view",
    enableDragDrop: "Enable drag & drop mode",
    disableDragDrop: "Disable drag & drop mode",
    level: "Level",
    levelOn: "On",
    levelOff: "Off",
    slat: "Slat Position",
    addEvent: "Add Event",
    editEvent: "Edit Event",
    deleteEvent: "Delete Event",
    time: "Time",
    duration: "Duration",
    rampTime: "Ramp Time",
    state: "State",
    weekdays: "Weekdays",
    channels: "Target Channels",
    condition: "Condition",
    astroSunrise: "Sunrise",
    astroSunset: "Sunset",
    astroOffset: "Astro Offset (min)",
    maxEntriesReached: "Maximum number of entries reached ({max})",
    confirmDelete: "Are you sure you want to delete this event?",
  },
  errors: {
    failedToChangeProfile: "Failed to change profile: {error}",
    failedToSaveSchedule: "Failed to save schedule: {error}",
    failedToPasteSchedule: "Failed to paste schedule: {error}",
    invalidSchedule: "Invalid schedule: {error}",
    failedToExport: "Failed to export schedule: {error}",
    failedToImport: "Failed to import schedule: {error}",
    invalidImportFile: "Invalid file format. Please select a JSON file.",
    invalidImportFormat: "Invalid JSON format in file.",
    invalidImportData: "Invalid schedule data: {error}",
    incompatibleEntity:
      "Entity {entity} is not a compatible schedule entity (requires schedule_type 'default' and schedule_api_version 'v1.0')",
    insufficientPermissions: "You don't have permission to perform this action.",
  },
  warnings: {
    title: "Validation Warnings",
    noWarnings: "No issues detected",
  },
  validationMessages: {
    blockEndBeforeStart: "Block {block}: End time is before start time",
    blockZeroDuration: "Block {block}: Block has zero duration",
    invalidStartTime: "Block {block}: Invalid start time",
    invalidEndTime: "Block {block}: Invalid end time",
    temperatureOutOfRange: "Block {block}: Temperature out of range ({min}-{max}°C)",
    invalidSlotCount: "Invalid number of slots: {count} (expected 13)",
    invalidSlotKey: "Invalid slot key: {key} (must be integer 1-13)",
    missingSlot: "Missing slot {slot}",
    slotMissingValues: "Slot {slot} missing ENDTIME or TEMPERATURE",
    slotTimeBackwards: "Slot {slot} time goes backwards: {time}",
    slotTimeExceedsDay: "Slot {slot} time exceeds 24:00: {time}",
    lastSlotMustEnd: "Last slot must end at 24:00",
    scheduleMustBeObject: "Schedule data must be an object",
    missingWeekday: "Missing weekday: {weekday}",
    invalidWeekdayData: "Invalid data for {weekday}",
    weekdayValidationError: "{weekday}: {details}",
  },
};
