// Re-export all config API functions and types from @hmip/panel-api
export {
  LINKABLE_INTERFACES,
  getDeviceIconUrl,
  listDevices,
  getFormSchema,
  getParamset,
  putParamset,
  sessionOpen,
  sessionSet,
  sessionUndo,
  sessionRedo,
  sessionSave,
  sessionDiscard,
  exportParamset,
  importParamset,
  getChangeHistory,
  clearChangeHistory,
  listDeviceLinks,
  getLinkFormSchema,
  getLinkParamset,
  putLinkParamset,
  addLink,
  removeLink,
  getLinkableChannels,
  getLinkProfiles,
  testLinkProfile,
  determineParameter,
  listScheduleDevices,
  getClimateSchedule,
  setClimateScheduleWeekday,
  setClimateActiveProfile,
  getDeviceSchedule,
  setDeviceSchedule,
  setScheduleEnabled,
  reloadDeviceConfig,
  getUserPermissions,
} from "@hmip/panel-api";

export type {
  MaintenanceData,
  DeviceInfo,
  ChannelInfo,
  FormSchema,
  FormSection,
  FormParameter,
  SubsetOption,
  SubsetGroup,
  PutResult,
  SessionState,
  SessionUndoRedoResult,
  SessionSaveResult,
  ExportResult,
  ImportResult,
  HistoryEntry,
  HistoryResult,
  LinkInfo,
  LinkableChannel,
  ResolvedProfile,
  LinkProfilesResponse,
  ScheduleDeviceInfo,
  ClimateScheduleData,
  DeviceScheduleData,
  UserPermissions,
} from "@hmip/panel-api";
